# Fuzzymatcher

In [5]:
import pandas as pd
import fuzzymatcher

In [2]:
%pip install fuzzymatcher

Collecting fuzzymatcher
  Downloading fuzzymatcher-0.0.6-py3-none-any.whl (15 kB)
Requirement already satisfied: pandas in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from fuzzymatcher) (1.5.3)
Collecting metaphone (from fuzzymatcher)
  Downloading Metaphone-0.6.tar.gz (14 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting python-Levenshtein (from fuzzymatcher)
  Downloading python_Levenshtein-0.23.0-py3-none-any.whl.metadata (3.8 kB)
Collecting rapidfuzz (from fuzzymatcher)
  Downloading rapidfuzz-3.6.1-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from fuzzymatcher) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas->fuzzymatcher) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas->fuzzymatcher) (1.26.3)
Requirement already satisfied: six>=1.5 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil->fuzzymatcher) (1.16.0)
Collecting Levenshtein==0.23.0 (from python-Levenshtein->fuzzymatcher)
  Downloading Levenshtein-0.23.0-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Downloading python_Levenshtein-0.23.0-py3-none-any.whl (9.4 kB)
Downloading Levenshtein-0.23.0-cp311-cp311-win_amd64.whl (101 kB)
   ---------------------------------------- 0.0/101.1 kB ? eta -:--:--
   ---------------------------------------- 101.1/101.1 kB 5.7 MB/s eta 0:00:00
Downloading rapidfuzz-3.6.1-cp311-cp311-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   --------- ------------------------------ 0.4/1.6 MB 11.8 MB/s eta 0:00:01
   -------------- ------------------------- 0.6/1.6 MB 7.2 MB/s eta 0:00:01
   -------------------- ------------------- 0.8/1.6 MB 6.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.2/1.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  1.6/1.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 6.9 MB/s eta 0:00:00
Building wheels for collected packages: metaphone
  Building wheel for metaphone (setup.py): started
  Building wheel for metaphone (setup.py): finished with status 'done'
  Created wheel for metaphone: filename=Metaphone-0.6-py3-none-any.whl size=13946 sha256=11a857646468aae03a68fcbb3166e7c158f4fd5d063a8ba12eb82d88b56096aa
  Stored in directory: c:\users\vstasik\appdata\local\pip\cache\wheels\08\cb\f9\3ce2de290cd1b6f10dd8ed4795f3dec4a835b02d2514f9b9d3
Successfully built metaphone
Installing collected packages: metaphone, rapidfuzz, Levenshtein, python-Levenshtein, fuzzymatcher
Successfully installed Levenshtein-0.23.0 fuzzymatcher-0.0.6 metaphone-0.6 python-Levenshtein-0.23.0 rapidfuzz-3.6.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
hospital_accounts = pd.read_csv('hospital_account_info.csv')
hospital_reinbursement = pd.read_csv('hospital_reimbursement.csv')

In [8]:
hospital_accounts

,Account_Num,Facility Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership
0,10605,SAGE MEMORIAL HOSPITAL,STATE ROUTE 264 SOUTH 191,GANADO,AZ,86505,APACHE,(928) 755-4541,Critical Access Hospitals,Voluntary non-profit - Private
1,24250,WOODRIDGE BEHAVIORAL CENTER,600 NORTH 7TH STREET,WEST MEMPHIS,AR,72301,CRITTENDEN,(870) 394-4113,Psychiatric,Proprietary
2,10341,DOUGLAS GARDENS HOSPITAL,5200 NE 2ND AVE,MIAMI,FL,33137,MIAMI-DADE,(305) 751-8626,Acute Care Hospitals,Voluntary non-profit - Private
3,81101,SUNCOAST BEHAVIORAL HEALTH CENTER,4480 51ST ST W,BRADENTON,FL,34210,MANATEE,(941) 792-2222,Psychiatric,Proprietary
4,39835,TREASURE VALLEY HOSPITAL,8800 WEST EMERALD STREET,BOISE,ID,83704,ADA,(208) 373-5000,Acute Care Hospitals,Proprietary
...,...,...,...,...,...,...,...,...,...,...
5334,92281,JEWISH HOSPITAL - SHELBYVILLE,727 HOSPITAL DRIVE,SHELBYVILLE,KY,40065,SHELBY,(502) 647-4300,Acute Care Hospitals,Voluntary non-profit - Private
5335,65248,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,MONTGOMERY,(937) 641-3450,Childrens,Voluntary non-profit - Private
5336,92377,NORTH TEXAS STATE HOSPITAL,6515 KEMP BLVD,WICHITA FALLS,TX,76308,WICHITA,(940) 692-1220,Psychiatric,Government - State
5337,71562,GULF BREEZE HOSPITAL,1110 GULF BREEZE PKWY,GULF BREEZE,FL,32561,SANTA ROSA,(850) 934-2000,Acute Care Hospitals,Voluntary non-profit - Other
5338,51586,I-70 COMMUNITY HOSPITAL,"105 HOSPITAL DRIVE, BUILDING B",SWEET SPRINGS,MO,65351,SALINE,(660) 335-4700,Critical Access Hospitals,Proprietary

In [9]:
hospital_reinbursement

,Provider_Num,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,839987,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,118,20855.61,5026.19,4115.52
1,519118,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,43,13289.09,5413.63,4490.93
2,733073,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,73,22261.60,4922.18,4021.79
3,201752,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,12,10901.33,5343.50,4284.17
4,678488,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,74,28117.95,5947.12,4819.53
...,...,...,...,...,...,...,...,...,...,...
2692,403227,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX,77845,37,20837.57,6389.76,3927.62
2693,797810,WALNUT HILL MEDICAL CENTER,7502 GREENVILLE AVENUE,DALLAS,TX,75231,52,32453.85,21927.08,4423.52
2694,611900,"BAY AREA REGIONAL MEDICAL CENTER, LLC",200 BLOSSOM STREET,WEBSTER,TX,77598,31,33006.84,19222.26,4497.16
2695,693781,RESOLUTE HEALTH HOSPITAL,"555 CREEKSIDE XING,",NEW BRAUNFELS,TX,78130,19,34370.00,9910.16,4531.37
2696,322584,BAYLOR SCOTT & WHITE MEDICAL CENTER - MARBLE F...,810 W HIGHWAY 71,MARBLE FALLS,TX,78654,18,17398.72,4650.44,3500.67

In [10]:
# defining which column match with which column (because they do not have the same name)
left_on = ["Facility Name", "Address", "City", "State"]
right_on = ["Provider Name", "Provider Street Address", "Provider City", "Provider State"]

In [12]:
# we use the fuzzymatcher library to find matches

matched_results = fuzzymatcher.fuzzy_left_join(hospital_accounts,
                                               hospital_reinbursement,
                                               left_on,
                                               right_on, left_id_col='Account_Num',
                                               right_id_col='Provider_Num')

In [13]:
# we reorganize the columns and we sort the result
cols = ["best_match_score", "Facility Name", "Provider Name", "Address", "Provider Street Address", "Provider City", "City", "Provider State", "State"]
matched_results[cols].sort_values(by=['best_match_score'], ascending=False).head(5)

,best_match_score,Facility Name,Provider Name,Address,Provider Street Address,Provider City,City,Provider State,State
78046,3.090931,RARITAN BAY MEDICAL CENTER PERTH AMBOY DIVISION,RARITAN BAY MEDICAL CENTER PERTH AMBOY DIVISION,530 NEW BRUNSWICK AVE,530 NEW BRUNSWICK AVE,PERTH AMBOY,PERTH AMBOY,NJ,NJ
532968,2.799072,ROBERT WOOD JOHNSON UNIVERSITY HOSPITAL,ROBERT WOOD JOHNSON UNIVERSITY HOSPITAL,ONE ROBERT WOOD JOHNSON PLACE,ONE ROBERT WOOD JOHNSON PLACE,NEW BRUNSWICK,NEW BRUNSWICK,NJ,NJ
78656,2.785132,AVERA MCKENNAN HOSPITAL & UNIVERSITY HEALTH CE...,AVERA MCKENNAN HOSPITAL & UNIVERSITY HEALTH CE...,1325 S CLIFF AVE POST OFFICE BOX 5045,1325 S CLIFF AVE POST OFFICE BOX 5045,SIOUX FALLS,SIOUX FALLS,SD,SD
242364,2.778860,JOHN T MATHER MEMORIAL HOSPITAL OF PORT JEFFE...,JOHN T MATHER MEMORIAL HOSPITAL OF PORT JEFFE...,75 NORTH COUNTRY ROAD,75 NORTH COUNTRY ROAD,PORT JEFFERSON,PORT JEFFERSON,NY,NY
447404,2.721425,MAYO CLINIC HEALTH SYSTEM - RED WING,MAYO CLINIC HEALTH SYSTEM IN RED WING,"701 HEWITT BOULEVARD, PO BOX 95","701 HEWITT BOULEVARD, PO BOX 95",RED WING,RED WING,MN,MN

In [14]:
# observing the worst matching scores
matched_results[cols].sort_values(by=['best_match_score'], ascending=True).head(5)

,best_match_score,Facility Name,Provider Name,Address,Provider Street Address,Provider City,City,Provider State,State
426391,-2.268231,CENTRO MEDICO WILMA N VAZQUEZ,BAPTIST MEDICAL CENTER EAST,CARR. 2 KM 39.5 ROAD NUMBER 2 BO ALGARROBO,400 TAYLOR ROAD,MONTGOMERY,VEGA BAJA,AL,PR
83263,-2.124071,DOCTOR CENTER HOSPITAL SAN FERNANDO DE LA CARO...,OVERLAKE HOSPITAL MEDICAL CENTER,EDIF JESUS T PINEIRO AVE FERNANDEZ JUNCOS BO P...,1035-116TH AVE NE,BELLEVUE,CAROLINA,WA,PR
42623,-2.106746,HOSPITAL ONCOLOGICO DR ISAAC GONZALEZ MARTINEZ,SCRIPPS MERCY HOSPITAL,BO. MONACILLOS CARR 22 CENTRO MEDICO DE PUERTO...,4077 5TH AVE,SAN DIEGO,SAN JUAN,CA,PR
450322,-2.050888,CENTRO DE SALUD CONDUCTUAL MENONITA-CIMA,MILFORD REGIONAL MEDICAL CENTER,CARR ESTATAL 14 INTERIOR SARGENTO GERARDO SANT...,14 PROSPECT STREET,MILFORD,AIBONITO,MA,PR
476283,-1.996508,ADMIN DE SERVICIOS MEDICOS PUERTO RIC,MAINE MEDICAL CENTER,BO MONACILLO CARR NUM 22,22 BRAMHALL ST,PORTLAND,SAN JUAN,ME,PR

One of the datasets contains data from Puerto Rico and the other one does not. It has create mismatches. This is why it is important to understand our data before performing the matching process. Sometimes, some cleaning is needed.

In [15]:
# looking at matches with a score that are not too high and not too low
matched_results[cols].query("best_match_score <= 0.80").sort_values(by=['best_match_score'], ascending=False).head(5)

,best_match_score,Facility Name,Provider Name,Address,Provider Street Address,Provider City,City,Provider State,State
518439,0.792471,METHODIST HOSPITAL SOUTH,SOUTH TEXAS REGIONAL MEDICAL CENTER,1905 HWY 97 EAST,1905 HWY 97 EAST,JOURDANTON,JOURDANTON,TX,TX
417036,0.791668,ADVENTIST HEALTH UKIAH VALLEY,UKIAH VALLEY MEDICAL CENTER,275 HOSPITAL DRIVE,275 HOSPITAL DRIVE,UKIAH,UKIAH,CA,CA
302935,0.787163,MADISON HEALTH,MADISON COUNTY HOSPITAL INC,210 NORTH MAIN STREET,210 NORTH MAIN STREET,LONDON,LONDON,OH,OH
388340,0.776632,PENN HIGHLANDS CLEARFIELD,CLEARFIELD HOSPITAL,809 TURNPIKE AVE,809 TURNPIKE AVE,CLEARFIELD,CLEARFIELD,PA,PA
493074,0.775573,MEMORIAL HOSPITAL AT GULFPORT,MEMORIAL HOSPITAL AT GULFPORT,4500 13TH STREET,4500 13TH ST-P O BOX 1810,GULFPORT,GULFPORT,MS,MS

We can see that the matches are more ambiguous : are ADVENTIST HEALTH UKIAH VALLEY and UKIAH VALLEY MEDICAL CENTER the same thing? Once again you need to really understand the data to answer this question.