In [1]:
%pip install splink

Collecting splink
  Downloading splink-3.9.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: Jinja2>=3.0.3 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (3.1.2)
Collecting altair<6.0.0,>=5.0.1 (from splink)
  Downloading altair-5.2.0-py3-none-any.whl.metadata (8.7 kB)
Collecting duckdb>=0.8.0 (from splink)
  Downloading duckdb-0.9.2-cp311-cp311-win_amd64.whl.metadata (798 bytes)
Requirement already satisfied: jsonschema<5.0,>=3.2 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (4.17.3)
Requirement already satisfied: pandas>1.3.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from splink) (1.5.3)
Collecting phonetics<2.0.0,>=1.0.5 (from splink)
  Downloading phonetics-1.0.5.tar.gz (8.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting sqlglot<19.0.0,>=13.0.0 (from splink)
  Downloading sqlglot-18.17.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from altair<6.0.0,>=5.0.1->splink) (1.26.3)
Requirement already satisfied: packaging in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from altair<6.0.0,>=5.0.1->splink) (23.2)
Collecting toolz (from altair<6.0.0,>=5.0.1->splink)
  Downloading toolz-0.12.0-py3-none-any.whl (55 kB)
     ---------------------------------------- 0.0/55.8 kB ? eta -:--:--
     ---------------------------------------- 55.8/55.8 kB ? eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from Jinja2>=3.0.3->splink) (2.1.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from jsonschema<5.0,>=3.2->splink) (23.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from jsonschema<5.0,>=3.2->splink) (0.20.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas>1.3.0->splink) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from pandas>1.3.0->splink) (2023.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\vstasik\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas>1.3.0->splink) (1.16.0)
Downloading splink-3.9.11-py3-none-any.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---- ----------------------------------- 0.5/3.7 MB 9.4 MB/s eta 0:00:01
   ------ --------------------------------- 0.6/3.7 MB 9.6 MB/s eta 0:00:01
   ----------- ---------------------------- 1.0/3.7 MB 8.3 MB/s eta 0:00:01
   -------------- ------------------------- 1.3/3.7 MB 7.7 MB/s eta 0:00:01
   -------------- ------------------------- 1.4/3.7 MB 7.1 MB/s eta 0:00:01
   ------------------ --------------------- 1.7/3.7 MB 6.4 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/3.7 MB 5.6 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/3.7 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.7 MB 6.2 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.7 MB 6.0 MB/s eta 0:00:01
   -------------------------------- ------- 3.0/3.7 MB 6.0 MB/s eta 0:00:01
   ----------------------------------- ---- 3.3/3.7 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  3.7/3.7 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  3.7/3.7 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 5.8 MB/s eta 0:00:00
Downloading altair-5.2.0-py3-none-any.whl (996 kB)
   ---------------------------------------- 0.0/996.9 kB ? eta -:--:--
   ---------------- ---------------------- 430.1/996.9 kB 13.5 MB/s eta 0:00:01
   ------------------ -------------------- 481.3/996.9 kB 10.0 MB/s eta 0:00:01
   ---------------------------------------  993.3/996.9 kB 7.9 MB/s eta 0:00:01
   ---------------------------------------  993.3/996.9 kB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 996.9/996.9 kB 5.7 MB/s eta 0:00:00
Downloading duckdb-0.9.2-cp311-cp311-win_amd64.whl (10.3 MB)
   ---------------------------------------- 0.0/10.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.3 MB 3.3 MB/s eta 0:00:04
   - -------------------------------------- 0.5/10.3 MB 7.0 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/10.3 MB 8.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/10.3 MB 8.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/10.3 MB 8.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/10.3 MB 9.0 MB/s eta 0:00:01
   --------- ------------------------------ 2.4/10.3 MB 9.0 MB/s eta 0:00:01
   ----------- ---------------------------- 2.9/10.3 MB 9.2 MB/s eta 0:00:01
   ------------ --------------------------- 3.2/10.3 MB 9.3 MB/s eta 0:00:01
   ------------- -------------------------- 3.4/10.3 MB 8.7 MB/s eta 0:00:01
   -------------- ------------------------- 3.7/10.3 MB 8.8 MB/s eta 0:00:01
   --------------- ------------------------ 4.0/10.3 MB 8.9 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.3 MB 8.7 MB/s eta 0:00:01
   ------------------- -------------------- 5.0/10.3 MB 9.1 MB/s eta 0:00:01
   --------------------- ------------------ 5.4/10.3 MB 8.9 MB/s eta 0:00:01
   ---------------------- ----------------- 5.7/10.3 MB 8.9 MB/s eta 0:00:01
   ----------------------- ---------------- 5.9/10.3 MB 8.8 MB/s eta 0:00:01
   ------------------------ --------------- 6.3/10.3 MB 8.8 MB/s eta 0:00:01
   -------------------------- ------------- 6.9/10.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------- ----------- 7.3/10.3 MB 9.0 MB/s eta 0:00:01
   ----------------------------- ---------- 7.6/10.3 MB 8.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.1/10.3 MB 9.0 MB/s eta 0:00:01
   -------------------------------- ------- 8.4/10.3 MB 8.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.7/10.3 MB 9.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.2/10.3 MB 8.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.7/10.3 MB 9.1 MB/s eta 0:00:01
   -------------------------------------- - 10.0/10.3 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------  10.3/10.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  10.3/10.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  10.3/10.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  10.3/10.3 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 10.3/10.3 MB 7.9 MB/s eta 0:00:00
Downloading sqlglot-18.17.0-py3-none-any.whl (324 kB)
   ---------------------------------------- 0.0/324.6 kB ? eta -:--:--
   --------------------------------------- 324.6/324.6 kB 10.1 MB/s eta 0:00:00
Building wheels for collected packages: phonetics
  Building wheel for phonetics (setup.py): started
  Building wheel for phonetics (setup.py): finished with status 'done'
  Created wheel for phonetics: filename=phonetics-1.0.5-py2.py3-none-any.whl size=8720 sha256=e920642d44441db80dfe1008beefae21158d63f128293f4cd2e625259b7c3988
  Stored in directory: c:\users\vstasik\appdata\local\pip\cache\wheels\40\63\73\d2c3bed2dc6df7c34ec9e1402761bed3519a4c0d152858b190
Successfully built phonetics
Installing collected packages: phonetics, toolz, sqlglot, duckdb, altair, splink
Successfully installed altair-5.2.0 duckdb-0.9.2 phonetics-1.0.5 splink-3.9.11 sqlglot-18.17.0 toolz-0.12.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
from splink.duckdb.linker import DuckDBLinker
from splink.duckdb.blocking_rule_library import block_on
import splink.duckdb.comparison_library as cl
import splink.duckdb.comparison_template_library as ctl

In [14]:
df_l = pd.read_csv('hospital_account_info.csv')
df_r = pd.read_csv('hospital_reimbursement.csv')

In [25]:
from splink.datasets import splink_datasets
df = splink_datasets.fake_1000

# Split a simple dataset into two, separate datasets which can be linked together.
df_l = df.sample(frac=0.5)
df_r = df.drop(df_l.index)

df_l.head(2)

downloading: https://raw.githubusercontent.com/moj-analytical-services/splink_datasets/master/data/fake_1000.csv
  download progress: 100 %	(==========)

,unique_id,first_name,surname,dob,city,email,cluster
74,74,Ronni,Begum,2003-10-15,London,r.b80@ellis-berry.com,22
463,463,Heenry,WilliaWms,2007-02-03,London,henry.w@miller-mitchell.info,117

In [26]:
from splink.duckdb.linker import DuckDBLinker
from splink.duckdb.blocking_rule_library import block_on
import splink.duckdb.comparison_library as cl
import splink.duckdb.comparison_template_library as ctl


settings = {
    "link_type": "link_only",
    "blocking_rules_to_generate_predictions": [
        block_on("first_name"),
        block_on("surname"),
    ],
    "comparisons": [
        ctl.name_comparison("first_name",),
        ctl.name_comparison("surname"),
        ctl.date_comparison("dob", cast_strings_to_date=True),
        cl.exact_match("city", term_frequency_adjustments=True),
        ctl.email_comparison("email", include_username_fuzzy_level=False),
    ],       
}

linker = DuckDBLinker([df_l, df_r], settings, input_table_aliases=["df_left", "df_right"])

In [27]:
linker.completeness_chart(cols=["first_name", "surname", "dob", "city", "email"])

alt.LayerChart(...)

In [28]:
deterministic_rules = [
    "l.first_name = r.first_name and levenshtein(r.dob, l.dob) &lt;= 1",
    "l.surname = r.surname and levenshtein(r.dob, l.dob) &lt;= 1",
    "l.first_name = r.first_name and levenshtein(r.surname, l.surname) &lt;= 2",
    "l.email = r.email"
]

linker.estimate_probability_two_random_records_match(deterministic_rules, recall=0.7)

ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.EQ'>. Line 1, Col: 65.
  l.first_name = r.first_name and levenshtein(r.dob, l.dob) &lt;= 1

In [29]:
linker.estimate_u_using_random_sampling(max_pairs=1e6, seed=1)

----- Estimating u probabilities using random sampling -----

Estimated u probabilities using random sampling

Your model is not yet fully trained. Missing estimates for:
    - first_name (no m values are trained).
    - surname (no m values are trained).
    - dob (no m values are trained).
    - city (no m values are trained).
    - email (no m values are trained).

In [30]:
session_dob = linker.estimate_parameters_using_expectation_maximisation(block_on("dob"))
session_email = linker.estimate_parameters_using_expectation_maximisation(block_on("email"))
session_first_name = linker.estimate_parameters_using_expectation_maximisation(block_on("first_name"))

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
l."dob" = r."dob"

Parameter estimates will be made for the following comparison(s):
    - first_name
    - surname
    - city
    - email

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:
    - dob

Iteration 1: Largest change in params was 0.586 in probability_two_random_records_match
Iteration 2: Largest change in params was 0.196 in probability_two_random_records_match
Iteration 3: Largest change in params was 0.086 in the m_probability of first_name, level `All other comparisons`
Iteration 4: Largest change in params was 0.0264 in probability_two_random_records_match
Iteration 5: Largest change in params was 0.0101 in probability_two_random_records_match
Iteration 6: Largest change in params was 0.00444 in probability_two_random_records_match
Iteration 7: Largest change in params was 0.00211 in probability_two_random_records_match
Iteration 8: Largest change in params was 0.00105 in probability_two_random_records_match
Iteration 9: Largest change in params was 0.000588 in probability_two_random_records_match
Iteration 10: Largest change in params was 0.000551 in the m_probability of first_name, level `All other comparisons`
Iteration 11: Largest change in params was 0.00104 in the m_probability of email, level `All other comparisons`
Iteration 12: Largest change in params was 0.00105 in the m_probability of first_name, level `All other comparisons`
Iteration 13: Largest change in params was 0.000773 in probability_two_random_records_match
Iteration 14: Largest change in params was 0.000474 in probability_two_random_records_match
Iteration 15: Largest change in params was 0.000271 in probability_two_random_records_match
Iteration 16: Largest change in params was 0.000152 in probability_two_random_records_match
Iteration 17: Largest change in params was 8.41e-05 in probability_two_random_records_match

EM converged after 17 iterations

Your model is not yet fully trained. Missing estimates for:
    - dob (no m values are trained).

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
l."email" = r."email"

Parameter estimates will be made for the following comparison(s):
    - first_name
    - surname
    - dob
    - city

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:
    - email

Iteration 1: Largest change in params was 0.694 in probability_two_random_records_match
Iteration 2: Largest change in params was 0.22 in probability_two_random_records_match
Iteration 3: Largest change in params was 0.0338 in probability_two_random_records_match
Iteration 4: Largest change in params was 0.0108 in probability_two_random_records_match
Iteration 5: Largest change in params was 0.00488 in probability_two_random_records_match
Iteration 6: Largest change in params was 0.00267 in probability_two_random_records_match
Iteration 7: Largest change in params was 0.00165 in probability_two_random_records_match
Iteration 8: Largest change in params was 0.00111 in probability_two_random_records_match
Iteration 9: Largest change in params was 0.000793 in the m_probability of surname, level `All other comparisons`
Iteration 10: Largest change in params was 0.000593 in the m_probability of surname, level `All other comparisons`
Iteration 11: Largest change in params was 0.000459 in the m_probability of surname, level `All other comparisons`
Iteration 12: Largest change in params was 0.000365 in the m_probability of surname, level `All other comparisons`
Iteration 13: Largest change in params was 0.000296 in the m_probability of surname, level `All other comparisons`
Iteration 14: Largest change in params was 0.000244 in the m_probability of surname, level `All other comparisons`
Iteration 15: Largest change in params was 0.000205 in the m_probability of surname, level `All other comparisons`
Iteration 16: Largest change in params was 0.000174 in the m_probability of surname, level `All other comparisons`
Iteration 17: Largest change in params was 0.000149 in the m_probability of surname, level `All other comparisons`
Iteration 18: Largest change in params was 0.000129 in the m_probability of surname, level `All other comparisons`
Iteration 19: Largest change in params was 0.000113 in the m_probability of surname, level `All other comparisons`
Iteration 20: Largest change in params was 9.9e-05 in the m_probability of surname, level `All other comparisons`

EM converged after 20 iterations

Your model is fully trained. All comparisons have at least one estimate for their m and u values

----- Starting EM training session -----

Estimating the m probabilities of the model by blocking on:
l."first_name" = r."first_name"

Parameter estimates will be made for the following comparison(s):
    - surname
    - dob
    - city
    - email

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules:
    - first_name

Iteration 1: Largest change in params was 0.287 in probability_two_random_records_match
Iteration 2: Largest change in params was 0.0396 in probability_two_random_records_match
Iteration 3: Largest change in params was 0.00684 in the m_probability of dob, level `Within 10 years`
Iteration 4: Largest change in params was 0.00118 in the m_probability of dob, level `Within 10 years`
Iteration 5: Largest change in params was 0.000224 in the m_probability of dob, level `Within 10 years`
Iteration 6: Largest change in params was 4.53e-05 in the m_probability of dob, level `Within 10 years`

EM converged after 6 iterations

Your model is fully trained. All comparisons have at least one estimate for their m and u values

In [31]:
results = linker.predict(threshold_match_probability=0.9)

In [32]:
results.as_pandas_dataframe(limit=5)

,match_weight,match_probability,source_dataset_l,source_dataset_r,unique_id_l,unique_id_r,first_name_l,first_name_r,gamma_first_name,surname_l,...,dob_l,dob_r,gamma_dob,city_l,city_r,gamma_city,email_l,email_r,gamma_email,match_key
0,3.234488,0.903956,df_left,df_right,57,51,Jayaned,Jayden,1,Bennett,...,2017-01-11,2017-01-11,5,swansea,Swansea,0,8jb88@king.com,None,-1,1
1,3.421364,0.914629,df_left,df_right,925,924,Muhammad,Muhammad,4,Patterson,...,2001-01-26,2000-12-27,3,Bournemouth,Bournehhoutm,0,None,None,-1,0
2,3.421364,0.914629,df_left,df_right,900,903,Aira,Aira,4,Cross,...,1999-01-14,1998-12-15,3,Newastle-upon-Tyne,Newcastle-upon-Tyne,0,a.cross58@browning-nguyen.com,None,-1,0
3,3.421364,0.914629,df_left,df_right,815,820,Logan,Logan,4,Morgan,...,1977-01-29,1976-12-31,3,Coventry,Cooventyr,0,None,loganmorgan43@mcbride-king.com,-1,0
4,3.421364,0.914629,df_left,df_right,37,42,Theodore,Theodore,4,Morris,...,1978-08-19,1978-09-18,3,Birmingham,Birgmhniam,0,t.m39@brooks-sawyer.com,None,-1,0