https://www.kaggle.com/datasets/nadyinky/sephora-products-and-skincare-reviews

In [35]:
import pandas as pd
import gensim

# Dataset extraction

In [3]:
df = pd.read_csv('product_info.csv')
df

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8489,P467659,Couture Clutch Eyeshadow Palette,1070,Yves Saint Laurent,2790,4.4286,7.0,NaN,NaN,NaN,...,0,0,0,NaN,Makeup,Eye,Eye Palettes,0,NaN,NaN
8490,P500874,L'Homme Eau de Parfum,1070,Yves Saint Laurent,2319,4.6367,556.0,2 oz / 60 mL,Size + Concentration + Formulation,2 oz / 60 mL eau de parfum spray,...,0,0,0,"['Layerable Scent', 'Woody & Earthy Scent']",Fragrance,Men,Cologne,1,129.0,129.0
8491,P504428,Mon Paris Eau de Parfum Gift Set,1070,Yves Saint Laurent,1475,5.0000,2.0,NaN,NaN,NaN,...,1,1,0,NaN,Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
8492,P504448,Y Eau de Parfum Gift Set,1070,Yves Saint Laurent,840,NaN,NaN,NaN,NaN,NaN,...,1,0,0,NaN,Fragrance,Value & Gift Sets,Cologne Gift Sets,0,NaN,NaN
8493,P505461,Candy Glaze Lip Gloss Stick Duo with Hyaluroni...,1070,Yves Saint Laurent,193,NaN,NaN,.11 oz / 3.2 mL,Color,NaN,...,1,0,1,"['Hyaluronic Acid', 'High Shine Finish', 'Plum...",Makeup,Lip,Lip Gloss,0,NaN,NaN

In [4]:
df.brand_name.unique()

array(['19-69', '54 Thrones', 'ABBOTT', 'Acqua di Parma', 'adwoa beauty',
       'AERIN', 'Algenist', 'Alpha-H', 'alpyn beauty', 'ALTERNA Haircare',
       'Ami Colé', 'amika', 'Anastasia Beverly Hills', 'Aquis',
       'Armani Beauty', 'Artist Couture', 'Atelier Cologne',
       'Augustinus Bader', 'Azzaro', 'bareMinerals', 'BeautyBio',
       'beautyblender', 'belif', 'Benefit Cosmetics', 'BERDOUES',
       'Bio Ionic', 'Biossance', 'Blinc', 'Bobbi Brown', 'Bon Parfumeur',
       'BondiBoost', 'Boy Smells', 'BREAD BEAUTY SUPPLY', 'Briogeo',
       'Bumble and bumble', 'BURBERRY', 'Buxom', 'By Rosie Jane',
       'caliray', 'Calvin Klein', 'CANOPY', 'Capri Blue',
       'Carolina Herrera', 'Caudalie', 'CAY SKIN', 'Ceremonia', 'CHANEL',
       'Charlotte Tilbury', 'Chloé', 'Christian Louboutin',
       'Christophe Robin', 'Cinema Secrets', 'Clarins', 'CLEAN RESERVE',
       'CLINIQUE', 'COLOR WOW', 'Commodity', 'Community Sixty-Six',
       'COOLA', 'Crown Affair', 'Curlsmith', 'dae', 'DAMDAM', 'Dame',
       'Danessa Myricks Beauty', 'Deborah Lippmann', 'DedCool',
       'DEREK LAM 10 CROSBY', 'DERMAFLASH', 'Dermalogica', 'Dior',
       'Dolce&Gabbana', 'DOMINIQUE COSMETICS', 'Donna Karan', 'dpHUE',
       'Dr. Barbara Sturm', 'Dr. Brandt Skincare',
       'Dr. Dennis Gross Skincare', 'Dr. Jart+',
       'Dr. Lara Devgan Scientific Beauty', 'Dr. Zenovia Skincare',
       'Drunk Elephant', 'Drybar', 'DUO', 'EADEM', 'Eight & Bob',
       'Ellis Brooklyn', 'Erno Laszlo', 'Estée Lauder', 'Evian',
       'Fable & Mane', 'FaceGym', 'Farmacy', 'Fashion Fair',
       'Fenty Beauty by Rihanna', 'Fenty Skin', 'First Aid Beauty',
       'Flora + Bast', 'Floral Street', 'FOREO', 'FORVR Mood',
       'Freck Beauty', 'fresh', 'ghd', 'Gisou', 'Givenchy', 'Glamnetic',
       'GLO Science', 'Glossier', 'Glow Recipe', 'Good Dye Young',
       'Google', 'goop', 'Grace Eleyae', 'Grande Cosmetics', 'Gucci',
       'GUERLAIN', 'GXVE BY GWEN STEFANI', 'HABIT', 'Hanni',
       'HAUS LABS BY LADY GAGA', 'Herbivore', 'HERETIC', 'HERMÈS',
       'Hourglass', 'House of Lashes', 'HUDA BEAUTY', 'HUM Nutrition',
       'Hyper Skin', 'Iconic London', 'IGK', 'ILIA', 'iluminage',
       'INC.redible', 'iNNBEAUTY PROJECT', 'innisfree',
       'Isle of Paradise', 'IT Cosmetics', 'Jack Black',
       'Jillian Dempsey', 'JIMMY CHOO', 'JLo Beauty', 'Jo Malone London',
       'Josie Maran', 'Jouer Cosmetics', 'Juicy Couture',
       'Juliette Has a Gun', 'JVN', 'K18 Biomimetic Hairscience', 'Kaja',
       'Kate McLeod', 'Kate Somerville', 'KAYALI', 'Kérastase',
       "Kiehl's Since 1851", 'KILIAN Paris', 'Koh Gen Do', 'Kopari',
       'KORA Organics', 'KORRES', 'Kosas', 'Kulfi', 'KVD Beauty',
       "L'Occitane", "L'Oreal Professionnel", 'La Mer', 'Lancôme',
       'LANEIGE', 'Laura Mercier', 'LAWLESS', 'lilah b.', 'Lilly Lashes',
       'Living Proof', 'LYS Beauty', 'MACRENE actives',
       'Maison Louis Marie', 'Maison Margiela', 'MAKE UP FOR EVER',
       'MAKEUP BY MARIO', 'MARA', 'Marc Jacobs Fragrances',
       'Mario Badescu', 'maude', 'Melanin Haircare', 'Melt Cosmetics',
       'MERIT', 'MILK MAKEUP', 'Mizani', 'Montblanc', 'Moon Juice',
       'Moroccanoil', 'Mount Lai', 'Mugler', 'Murad', 'NAILS INC.',
       'Narciso Rodriguez', 'NARS', 'Natasha Denona', 'Naturally Serious',
       'Nécessaire', 'NEST New York', 'NUDESTIX', 'NuFACE', 'Nutrafol',
       'Olaplex', 'OLEHENRIKSEN', 'ONE/SIZE by Patrick Starrr', 'Oribe',
       'Origins', 'OTHERLAND', 'OUAI', 'Overose', 'Paco Rabanne',
       'PAT McGRATH LABS', 'PATRICK TA', 'PATTERN by Tracee Ellis Ross',
       "Paula's Choice", 'Peace Out', 'Peter Thomas Roth', 'philosophy',
       'PHLUR', 'PMD', 'Prada', 'Prima', 'PROVEN Skincare', 'Pureology',
       'Rahua', 'Ralph Lauren', 'RANAVAT', 'Rare Beauty by Selena Gomez',
       'REFY', 'REN Clean Skincare', 'RIES', 'rms beauty', 'ROSE INC',
       'ROSE Ingleton MD', 'Rosebud Perfume Co.',
       'Rossano Ferretti Parma', 'Saie', 'Saint Jane Beauty',
       'SEPHORA COLLECTION', 'Sephora Favorites',
       'Shani Darden Skin Care', 'Shiseido', 'shu uemura',
       'SIMIHAZE BEAUTY', 'SK-II', 'Skin Laundry', 'Skinfix', 'SKYLAR',
       'Slip', 'Smashbox', 'SOBEL SKIN Rx', 'Sol de Janeiro',
       'Soleil Toujours', 'St. Tropez', 'stila', 'StriVectin',
       'Sulwhasoo', 'Summer Fridays', 'SUNDAY II SUNDAY', 'Sunday Riley',
       'Supergoop!', 'Susteau', 'T3', 'TAN-LUXE', 'tarte', 'Tata Harper',
       'Tatcha', 'The 7 Virtues', 'The INKEY List', 'The Maker',
       'The Nue Co.', 'The Ordinary', 'The Original MakeUp Eraser',
       'The Outset', 'The Phluid Project', 'TOCCA', 'TOM FORD',
       'Too Faced', 'Topicals', 'Touchland', 'Tower 28 Beauty',
       'TULA Skincare', 'TWEEZERMAN', 'Urban Decay', 'Valentino',
       'Vegamour', 'Velour Lashes', 'Verb', 'Versace', 'Viktor&Rolf',
       'Violet Voss', 'Viori', 'Virtue', 'Viseart', 'VOLUSPA',
       'Wander Beauty', 'WASO', 'Westman Atelier', 'Wishful',
       'World of Chris Collins', 'Youth To The People',
       'Yves Saint Laurent'], dtype=object)

In [5]:
LVMH_beauty_brands = ["Acqua di Parma", "Benefit Cosmetics", "Dior", "Fenty Beauty by Rihanna", "Fenty Skin", "fresh", "Givenchy", "GUERLAIN", "KVD Beauty", "MAKE UP FOR EVER", "OLEHENRIKSEN"]

In [7]:
mask = df['brand_name'].isin(LVMH_beauty_brands)
filtered_df = df[mask]

In [8]:
print(filtered_df)

     product_id                                       product_name  brand_id  \
31      P443401          Blu Mediterraneo Mini Eau de Toilette Set      5847
32      P307804                                   Mirto di Panarea      5847
33      P375388                                   Arancia di Capri      5847
34      P163604                                            Colonia      5847
35      P252213                                    Magnolia Nobile      5847
...         ...                                                ...       ...
5617    P454800                       Mini Glow2OH Dark Spot Toner      5674
5618    P503933  The Night Time Edit- Jenna Rennert X OLEHENRIKSEN      5674
5619    P503876                        OLE Glow Icons Skincare Set      5674
5620    P504035  Mini BeamCream Smoothing Body Moisturizer with...      5674
5621    P504032       Glow Strong Mini Moisturizer + Eye Cream Duo      5674

          brand_name  loves_count  rating  reviews            size  \
31    Acqua di Parma         7290  3.3333     12.0  5 x 0.16oz/5mL
32    Acqua di Parma         5658  4.4359     39.0     1 oz/ 30 mL
33    Acqua di Parma         4812  3.9459     37.0        1oz/30mL
34    Acqua di Parma         4157  4.2125     80.0  3.4 oz/ 100 mL
35    Acqua di Parma         3378  4.2791     43.0  3.4 oz/ 101 mL
...              ...          ...     ...      ...             ...
5617    OLEHENRIKSEN            0  4.5000      8.0   2.2 oz/ 65 mL
5618    OLEHENRIKSEN         1927  3.4000      5.0             NaN
5619    OLEHENRIKSEN         1997  3.7500      4.0             NaN
5620    OLEHENRIKSEN         1034  4.0000      1.0  1.7 oz / 50 mL
5621    OLEHENRIKSEN           64     NaN      NaN             NaN

                          variation_type                      variation_value  \
31                                  Size                       5 x 0.16oz/5mL
32    Size + Concentration + Formulation                          1 oz/ 30 mL
33    Size + Concentration + Formulation                             1oz/30mL
34    Size + Concentration + Formulation  3.4 oz/ 100 mL Eau de Cologne Spray
35    Size + Concentration + Formulation                       3.4 oz/ 101 mL
...                                  ...                                  ...
5617                                Size                        2.2 oz/ 65 mL
5618                                 NaN                                  NaN
5619                                 NaN                                  NaN
5620                                Size                       1.7 oz / 50 mL
5621                                 NaN                                  NaN

      ... online_only out_of_stock  sephora_exclusive  \
31    ...           1            0                  0
32    ...           1            0                  0
33    ...           1            0                  0
34    ...           1            0                  0
35    ...           1            1                  0
...   ...         ...          ...                ...
5617  ...           0            0                  1
5618  ...           0            0                  1
5619  ...           0            0                  1
5620  ...           1            0                  1
5621  ...           0            0                  1

                                             highlights  primary_category  \
31          ['Unisex/ Genderless Scent', 'Fresh Scent']         Mini Size
32          ['Unisex/ Genderless Scent', 'Fresh Scent']         Fragrance
33          ['Unisex/ Genderless Scent', 'Fresh Scent']         Fragrance
34          ['Unisex/ Genderless Scent', 'Fresh Scent']         Fragrance
35                                                  NaN         Fragrance
...                                                 ...               ...
5617  ['Vegan', 'Good for: Dullness/Uneven Texture',...          Skincare
5618  ['Vegan', 'Good for: Dullness/Uneven Texture',...          Skincare
5619  ['Vegan', 'Good for: Dullness/Uneven Texture',...          Skincare
5620  ['Vegan', 'Good for: Dullness/Uneven Texture',...       Bath & Body
5621  ['Vegan', 'Good for: Loss of firmness', 'Good ...          Skincare

      secondary_category         tertiary_category  child_count  \
31             Fragrance                       NaN            0
32                 Women                   Perfume            1
33                 Women                   Perfume            0
34                   Men                   Cologne            0
35                 Women                   Perfume            0
...                  ...                       ...          ...
5617           Mini Size                       NaN            0
5618   Value & Gift Sets                       NaN            0
5619   Value & Gift Sets                       NaN            0
5620   Body Moisturizers  Body Lotions & Body Oils            0
5621   Value & Gift Sets                       NaN            0

      child_max_price  child_min_price
31                NaN              NaN
32              214.0            210.0
33                NaN              NaN
34                NaN              NaN
35                NaN              NaN
...               ...              ...
5617              NaN              NaN
5618              NaN              NaN
5619              NaN              NaN
5620              NaN              NaN
5621              NaN              NaN

[632 rows x 27 columns]

In [9]:
filtered_df.to_csv('LVMH_houses.csv', index=False)

In [4]:
df = pd.read_csv("LVMH_houses.csv")
df

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P443401,Blu Mediterraneo Mini Eau de Toilette Set,5847,Acqua di Parma,7290,3.3333,12.0,5 x 0.16oz/5mL,Size,5 x 0.16oz/5mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Fresh Scent']",Mini Size,Fragrance,NaN,0,NaN,NaN
1,P307804,Mirto di Panarea,5847,Acqua di Parma,5658,4.4359,39.0,1 oz/ 30 mL,Size + Concentration + Formulation,1 oz/ 30 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Fresh Scent']",Fragrance,Women,Perfume,1,214.0,210.0
2,P375388,Arancia di Capri,5847,Acqua di Parma,4812,3.9459,37.0,1oz/30mL,Size + Concentration + Formulation,1oz/30mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Fresh Scent']",Fragrance,Women,Perfume,0,NaN,NaN
3,P163604,Colonia,5847,Acqua di Parma,4157,4.2125,80.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL Eau de Cologne Spray,...,1,0,0,"['Unisex/ Genderless Scent', 'Fresh Scent']",Fragrance,Men,Cologne,0,NaN,NaN
4,P252213,Magnolia Nobile,5847,Acqua di Parma,3378,4.2791,43.0,3.4 oz/ 101 mL,Size + Concentration + Formulation,3.4 oz/ 101 mL,...,1,1,0,NaN,Fragrance,Women,Perfume,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,P454800,Mini Glow2OH Dark Spot Toner,5674,OLEHENRIKSEN,0,4.5000,8.0,2.2 oz/ 65 mL,Size,2.2 oz/ 65 mL,...,0,0,1,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Skincare,Mini Size,NaN,0,NaN,NaN
628,P503933,The Night Time Edit- Jenna Rennert X OLEHENRIKSEN,5674,OLEHENRIKSEN,1927,3.4000,5.0,NaN,NaN,NaN,...,0,0,1,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN
629,P503876,OLE Glow Icons Skincare Set,5674,OLEHENRIKSEN,1997,3.7500,4.0,NaN,NaN,NaN,...,0,0,1,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN
630,P504035,Mini BeamCream Smoothing Body Moisturizer with...,5674,OLEHENRIKSEN,1034,4.0000,1.0,1.7 oz / 50 mL,Size,1.7 oz / 50 mL,...,1,0,1,"['Vegan', 'Good for: Dullness/Uneven Texture',...",Bath & Body,Body Moisturizers,Body Lotions & Body Oils,0,NaN,NaN
631,P504032,Glow Strong Mini Moisturizer + Eye Cream Duo,5674,OLEHENRIKSEN,64,NaN,NaN,NaN,NaN,NaN,...,0,0,1,"['Vegan', 'Good for: Loss of firmness', 'Good ...",Skincare,Value & Gift Sets,NaN,0,NaN,NaN

# Gensim

In [7]:
df["product_name"].shape

(632,)

In [10]:
df['product_name_processed'] = df['product_name'].apply(lambda x: gensim.utils.simple_preprocess(x))

In [23]:
df['product_name_processed'].head(20)

0     [blu, mediterraneo, mini, eau, de, toilette, set]
1                                  [mirto, di, panarea]
2                                  [arancia, di, capri]
3                                             [colonia]
4                                    [magnolia, nobile]
5                               [yuzu, eau, de, parfum]
6                                [oud, eau, de, parfum]
7                                    [colonia, essenza]
8                                [buongiorno, diffuser]
9                   [colonia, alcohol, free, deodorant]
10                                      [colonia, pura]
11                         [arancia, di, capri, candle]
12                           [fico, di, amalfi, candle]
13                  [aperitivo, in, terrazza, diffuser]
14                        [luce, di, colonia, diffuser]
15                                     [hoola, bronzer]
16       [the, porefessional, pore, minimizing, primer]
17               [they, re, real, lengthening, mascara]
18      [gimme, brow, tinted, volumizing, eyebrow, gel]
19    [precisely, my, brow, pencil, waterproof, eyeb...
Name: product_name_processed, dtype: object

In [14]:
model = gensim.models.Word2Vec(
    df['product_name_processed'].tolist(),
    window=10,
    min_count=1,
    workers=-1
)

In [25]:
w1 = "porefessional"
model.wv.most_similar(positive=w1)

[('powder', 0.3488037586212158),
 ('microfinishing', 0.3128747344017029),
 ('balm', 0.26485419273376465),
 ('floral', 0.26017147302627563),
 ('everlasting', 0.24976040422916412),
 ('on', 0.2482849359512329),
 ('brush', 0.2476501166820526),
 ('felt', 0.24733999371528625),
 ('blur', 0.24393346905708313),
 ('air', 0.24315863847732544)]

In [26]:
query = "porefessional"
query_processed = gensim.utils.simple_preprocess(query)

In [27]:
query_embedding = model.wv[query_processed]

In [28]:
df['similarity'] = df['product_name_processed'].apply(
    lambda x: model.wv.n_similarity(query_processed, x)
)

In [29]:
most_similar_documents = df.sort_values(by='similarity', ascending=False)['product_name'].tolist()

In [30]:
print(most_similar_documents)

['The POREfessional Hydrating Primer', 'The POREfessional Pore Minimizing Primer', 'Mini The POREfessional Hydrating Primer', 'Mini The POREfessional Pore Minimizing Primer', '124 Powder Kabuki Brush', 'Ultra HD Microfinishing Pressed Powder', 'The POREfessional: Super Setter Pore-Minimizing Setting Spray', 'The POREfessional Speedy Smooth Mask', 'The POREfessional Smooth Sip Lightweight Gel-Cream Moisturizer', 'Mini The POREfessional: Super Setter Setting Spray', '126 Medium Powder Brush', 'Hello Happy Velvet Powder Foundation', 'Mini Ultra HD Microfinishing Pressed Powder', 'Abeille Royale Intense Repair Youth Oil in Balm', 'The POREfessional Good Cleanup Foaming Cleanser', 'The POREfessional Tight ’n Toned Pore-Refining AHA+PHA Toner', 'Météorites Powder Brush', 'Mini The POREfessional Tight ’n Toned Pore-Refining AHA+PHA Toner', 'Mini The POREfessional Good Cleanup Foaming Cleanser', 'Multitasking Cheek Brush for Powder Blush, Bronzer & Highlighter', 'Lock-It Powder Foundation Refills', 'Powder Puff Setting Brush 170', 'Lock-It Powder Foundation', 'Sugar Hydrating Lip Balm', 'Fairy Bomb Shimmer Powder', 'Le Rouge Universal 24H Hydration Lip Balm', 'Lock-It Finishing Powder Refill', 'The POREfessional: Lite Primer Water-Based Pore Primer', "J'adore Soap", 'Ultra HD Microfinishing Loose Powder', 'Invisimatte Instant Setting + Blotting Powder', "Pro Filt'r Instant Retouch Setting Powder", 'The POREfessional: Mini Lite Primer Water-Based Pore Primer', 'The POREfessional Deep Retreat Pore-Clearing Clay Mask', 'Mini The POREfessional Package Deal pore primer & pore care value set', 'Invisimatte Refill Instant Setting + Blotting Powder', 'Brow MVP Sculpting Wax Pencil & Styler', 'Rouge Dior Lip Balm Refill', 'Météorites Illuminating Powder Pearls', '130 Large Powder Brush', 'Mini Pro Filt’r Instant Retouch Setting Powder', 'Diorshow Waterproof Mascara', 'Sugar Advanced Lip Balm Intense Hydration Treatment', 'Pro Filt’r Soft Matte Longwear Powder Foundation', 'Everlasting Lip Liner', 'Baby ’Buki Brush 165', 'Mini The POREfessional Deep Retreat Pore-Clearing Clay Mask', 'Rouge Dior Lip Balm', 'Grooming Tweezer & Brush', '158 Double Ended Sculpting Brush', 'Light Velvet Air Shine-Control Refreshing Spray', 'Mini Ultra HD Microfinishing Loose Powder', 'Sugar Lip Balm Hydrating Treatment', 'Sculpting Bronzer Brush 195', 'The POREfessional Get Unblocked Makeup-Removing Cleansing Oil', '274 Double Ended Eyebrow Brush', 'Volume Disturbia Mascara', 'Portable Touchup Brush 130', 'Abeille Royale Advanced Youth Watery Oil', 'Mini Diorshow Mascara Duo Set', 'Brow MVP Ultra Fine Brow Pencil & Styler', 'WANDERful World Silky-Soft Powder Blush', 'Abeille Royale Scalp & Hair Youth Oil in Serum', 'Hydra Life Deep Hydration Sorbet Water Essence', 'Hydra Life Intense Sorbet Crème Moisturizer', 'Face & Body Kabuki Brush 160', 'Lock-It Refillable Mattifying Pressed Finishing Powder', 'Mini Light Velvet Air Shine-Control Refreshing Spray', 'Fresh Life Body Lotion', 'Everlasting Blush', 'Mini The POREfessional Get Unblocked Makeup-Removing Cleansing Oil', 'Face Shaping Brush 125', 'Lock-It Setting Powder', '160 Blush Brush', "Diorshow Pump 'N' Volume Mascara", "Diorshow Pump'N'Volume Waterproof Mascara", 'Dandelion Baby-Pink Blush', 'Star Lit Powder', 'Mini Abeille Royale Advanced Youth Watery Oil', "J'adore Huile Divine - Dry Silky Body & Hair Oil", 'Cheek-Hugging Highlight Brush 120', "J'adore Hair Mist", '250 Extra Fine Eyeliner Brush', 'Shade + Light Refillable Powder Face Contour Palette', 'Hesperides Grapefruit Body Lotion', 'Smoky Extravagant Mascara', 'Rouge Interdit Intense Silk Satin Matte Lipstick Refills', 'Capture Youth Intense Rescue Age-Delay Revitalizing Oil-Serum', 'Mini Dandelion Baby-Pink Blush', 'HD Skin Matte Velvet Undetectable Longwear Blurring Powder Foundation', "J'adore Body Milk", 'Buffing Foundation Brush 112', 'Aqua Allegoria Mandarine Basilic Eau de Toilette', 'Irresistible Eau de Toilette Fraiche', 'Irresistible Eau De Toilette Fraiche', 'Mister Brow Groom Universal Brow Setter', 'Cheek Hugging Bronzer Brush 190', 'Aqua Smoky Extravagant Waterproof Mascara', "Pro Filt'r Hydrating Longwear Foundation", 'Aqua Allegoria Nerolia Vetiver Eau de Toilette', 'Sauvage Eau de Toilette Gift Set', '#109 HD Skin Foundation Brush', '#70 Pomade Brow Brush', "Pro Kiss'r Luscious Lip Balm", 'Brow Pomade Eyebrow Brush', 'Lotus Anti-Aging Night Moisturizer', 'Capture Totale Le Sérum Anti-Aging Serum', "Pro Filt'r Instant Retouch Primer", 'Mascara Power Pair Extreme Lengthening Mascara Set', 'Dandelion Twinkle Highlighter', 'Full-Bodied Foundation Brush 110', 'Kabuki-Buff Foundation Brush 115', 'Professional Bag', 'Cookie and Tickle Powder Highlighters', 'Liner Disturbia Felt Tip Eyeliner', 'Precisely, My Brow Pencil Waterproof Eyebrow Definer', 'Pro Filt’r Instant Retouch Longwear Liquid Concealer', 'Artist Face Color Highlight, Sculpt and Blush Powder', 'Abeille Royale Anti-Aging Fortifying Lotion Toner', 'Capture Youth Glow Booster Age-Delay Illuminating Serum', 'Ultra HD Invisible Cover Stick Foundation', 'Hydra Life Fresh Sorbet Crème Moisturizer', 'Mini Pro Filt’r Instant Retouch Primer', "J'adore Eau de Parfum Roller-pearl", 'Body Sauce Body Luminizing Tint', 'Mini Lotus Anti-Aging Night Moisturizer', "J'adore Eau de Parfum", 'Rose Petal-Soft Deep Hydration Lip Balm', 'Diorshow Brow Styler Ultra-Fine Precision Brow Pencil', 'Dior Forever Natural Powder Bronzer', 'Diorshow 24h Buildable Volume Mascara', 'Le Rouge Deep Velvet Matte Lipstick', 'Capture Totale Intensive Essence Lotion', 'Get REAL Duo Lengthening Mascara Value Set', 'Mini Precisely, My Brow Pencil Waterproof Eyebrow Definer', 'Parure Gold 24K Radiance Primer', 'Abeille Royale Bestsellers Travel Set', 'HD Skin Undetectable Longwear Foundation', 'Prep & Treat Lip Care Gift Set', 'What it Dew Makeup Refreshing Spray', 'Diorshow On Stage Waterproof Liquid Eyeliner', 'MiniMist & Fix Hydrating Setting Spray', 'Hello Happy Flawless Brightening Foundation SPF 15', 'Le Rouge Sheer Velvet Matte Lipstick Customized Refills', 'Mist & Fix 24HR Hydrating Setting Spray', 'Abeille Royale Anti-Aging Double R Advanced Serum', 'Capture Youth Age-Delay Advanced Crème', 'Rouge Interdit Intense Silk Satin Matte Lipstick', 'Mon Guerlain Eau de Parfum Intense', 'Sugar Mint Rush Freshening Lip Treatment', 'Lip Liner', 'Mini Dandelion Twinkle Highlighter', 'Plush Eyeshadow Brush 240', "Pro Filt'r Hydrating Primer", 'Hydra Life Balancing Hydration 2 in 1 Sorbet Water', 'Ultra HD Matte Setting Powder', 'BACKSTAGE Face & Body Foundation', 'Hoola Bronzer', 'POWmade Waterproof Brow Pomade', '24-HR Brow Setter Clear Brow Gel with Lamination Effect', 'Mini Mist & Fix 24HR Hydrating Setting Spray', 'Strength Trainer Peptide Boost Moisturizer', 'Fico di Amalfi Candle', 'Mini HD Skin Undetectable Longwear Foundation', 'Tapered Blending Brush 210', 'Fly Baby Mini Eye Primer and Liner Set', 'Lock-It Hydrating Primer', 'Gloss Bomb Universal Lip Luminizer', 'Mini Hello Happy Flawless Brightening Foundation SPF 15', 'Mini 24-HR Brow Setter Clear Brow Gel with Lamination Effect', 'Benetint Liquid Lip Blush & Cheek Tint', 'KissKiss Bee Glow Lipstick Balm', 'Pro Filt’r Soft Matte Longwear Liquid Foundation', "Mini Pro Filt'r Hydrating Primer", 'Rose Perfecto Lip Balm 24H Hydration', 'Prisme Libre Loose Setting and Finishing Powder', 'Good Apple Lightweight Full-Coverage Cream Foundation Balm', 'Gloss Bomb Dip Clip-On Luminizer', 'Météorites Primer Perfecting Pearls', 'Pre-Show Glow Instant Retexturizing 10% AHA Treatment + Reusable Applicator', 'Step 1 Primer Hydra Booster', 'Lotus Anti- Aging Daily Moisturizer', 'Verbena Oval Soap', 'Matte Velvet Skin Full Coverage Foundation', 'Mini Lotus Youth Preserve Moisturizer', 'The Night Time Edit- Jenna Rennert X OLEHENRIKSEN', 'Lip Glow Oil', 'Abeille Royale Night Cream', 'Step 1 Primer Pore Minimizer', 'Hello Happy Flawless Brightening Foundation', 'Pink Collection Le Rouge Sheer Velvet Matte Lipstick', 'Full Frontal Volume, Lift & Curl Mascara', 'Star Lit Diamond Powder', 'Glossy Posse Volume 5.0 Lip Gloss Bomb Trio', 'Dewtopia 5% AHA Firming Night Crème', 'Aqua Resist Smoky Eyeshadow Stick', 'Lotus Youth Preseve Rescue Mask Mini', 'Aqua Allegoria Pamplelune Eau de Toilette', 'Hypnotic Poison Roller-Pearl', 'Rose Perfecto Tinted Liquid Balm', 'Boi-ing Industrial Strength Full Coverage Cream Concealer', 'KissKiss Shine Bloom Lipstick Balm', 'Mini Strength Trainer Peptide Boost Moisturizer', 'Dior Forever Couture Luminizer Highlighter Powder', 'Mini Full Frontal Volume, Lift & Curl Mascara', 'Lip Maximizer Serum', 'Terracotta Light Healthy Glow Bronzer', 'Le Rouge Sheer Velvet Matte Lipstick', 'Diorshow Iconic Overcurl Waterproof Mascara', "They're Real! Lengthening Mascara", 'Dior Forever Loose Cushion Powder', 'Capture Totale Intensive Night Restorative Crème', 'Aqua Allegoria Rosa Rossa Eau de Toilette', 'Cold Plunge Pore Remedy Moisturizer with BHA/LHA', 'Ultra HD Self-Setting Medium Coverage Concealer', 'Stunna Lip Paint Longwear Fluid Lip Color', "J'adore Parfum d'Eau", 'Hydrating Skincare Gift Set', 'Hypnotic Poison', 'Rouge Artist Shine On Lipstick', "L'Interdit Eau de Toilette", 'Diorshow Iconic Overcurl Mascara', 'Gentleman Eau de Toilette', 'Mini Step 1 Primer Hydra Booster', 'Kitten Mini: Glamrok Shade + Light Eyeshadow Quad', 'Treat & Tint Mini Lip Care Gift Set', 'Milk Body Lotion', 'Arancia di Capri Candle', 'Terracotta Le Teint Healthy Glow Foundation', 'Miss Dior Blooming Bouquet Lifestyle Gift Set', 'Capture Youth Serum Collection', "Sun Stalk'r Instant Warmth Bronzer", 'Citron de Vigne Body Lotion', 'BACKSTAGE Face & Body Primer', "Mini Pro Filt'r Soft Matte Foundation", 'Sauvage Eau de Toilette', 'Mini Step 1 Primer Pore Minimizer', 'Ultra HD Invisible Cover Cream Foundation Palette', 'Letters to Lashes Mascara Set', "Fenty Skin Travel Size Start'r Set", 'Aqua Lip Waterproof Lipliner Pencil', 'The Body Duo Mini Body Scrub + Moisturizer Essentials', 'BADgal Goodies Volumizing Mascara Value Set', 'Match Stix Shimmer Skinstick', 'Vitamin C Glow Moisturizer', 'Aqua Resist Waterproof Eyebrow Definer Pencil', 'Homme Eau de Toilette', 'Hot Couture Eau de Toilette', 'Eye and Lip Makeup Remover', 'Sauvage Deodorant Stick', 'Dior Forever Skin Glow Foundation SPF 15', 'Homme Deodorant Stick', 'Cica Recover & Repair Multi-Use Balm', 'Lock-It Full-Coverage Long-Wear Matte Liquid Foundation', 'Precision Concealer Brush 180', "Mini They're Real! Lengthening Mascara", 'Pro Sculpting Face Palette', 'Capture Totale Firming & Wrinkle-Correcting Cream', 'Arancia di Capri', 'Mini Roller Express Curling Mascara & Liquid Eyeliner Set', 'Eaze Drop Blurring Skin Tint', 'Banana Bright Face Primer', 'Diorshow OnSet Brow Gel', 'Miss Dior Eau de Toilette Roller-pearl', 'Butta Drop Whipped Oil Hydrating Body Cream', 'Aqua Allegoria Bergamote Calabria Eau de Toilette', 'Mini Rouge Dior Lipstick Set', "J'adore Eau Lumière Eau de Toilette Roller-pearl", 'Mini Lock-It Full-Coverage Long-Wear Matte Liquid Foundation', 'Lock-It Vegan Pore-Refining Hydrating Primer with Rice Water', 'Ink Liner Waterproof Felt-Tip Liquid Eyeliner', 'Blu Mediterraneo Mini Eau de Toilette Set', 'Umbrian Clay Pore Purifying Face Mask', 'Boi-ing Cakeless Full Coverage Waterproof Liquid Concealer', 'Firmly Yours Dry Body Oil with Peptides', 'Sauvage Shaving Gel', 'Capture Youth Age-Delay Progressive Peeling Crème', 'Sauvage Deodorant Spray', 'Capture Youth Age-Delay Advanced Eye Treatment', 'Brow Microfilling Eyebrow Pen', 'BACKSTAGE Glow Face Palette', 'Buongiorno Diffuser', 'Prisme Libre Skin-Caring 24H Hydrating + Radiant + Correcting Creamy Concealer', 'Sinner Eau de Parfum', "Let's Get Luminous Brightening Essentials Set", "Pro Filt'r Mattifying Primer", "J'adore eau de parfum infinissime Roller-Pearl", 'Butta Drop Whipped Oil Hydrating Body Cream Mini', 'BROWVO! Conditioning Eyebrow Primer', 'Sugar Lip Polish Exfoliator', 'Irresistible Eau de Parfum', 'Sauvage Very Cool Spray', 'Body Lava Body Luminizer', 'Lotus Youth Preserve Rescue Mask', 'Ultra HD Skin Booster', 'Mini Umbrian Clay Pore Purifying Face Mask', 'Miss Dior Body Oil', 'Miss Dior Eau de Toilette', 'Acids Done Bright Smoothing Skincare Set', 'Dior Skin Mattifying Papers', 'Oud Eau de Parfum', "J'adore Eau Lumière Eau de Toilette", 'Dior Forever Matte Foundation SPF 15', 'Miss Dior Eau de Parfum Set', 'Capture Youth Plump Filler Age-Delay Plumping Serum', 'Aqua Allegoria Pera Granita Eau de Toilette', 'Forever Natural Velvet Matte Compact Foundation', 'Backstage Concealer', 'Rouge Dior Lipstick Refill', "Mini Pro Filt'r Mattifying Primer", "Pro Filt'r Amplifying Eye Primer", 'Fahrenheit', 'C-Rush Vitamin C Gel Moisturizer', 'Vitamin Nectar Glow Juice Antioxidant Face Serum', 'BACKSTAGE Rosy Glow Blush', 'Fluff Up Brow Flexible Brow-Texturizing Wax', 'Gimme Brow Goals Volumizing Brow Gel & Pencil Duo', 'Dior Forever Velvet Veil Matte Primer', 'Sugar Lemon Body Lotion', 'Football Sponge', 'Prisme Libre Skin-Caring Glow Foundation', '216 Medium Precision Eye Blender Brush', 'Aqua Seal', 'Miss Dior Blooming Bouquet Roller-pearl', 'Brown Sugar Body Polish Exfoliator', 'Mini Cleansing Bar Duo + Case', 'Gloss Bomb Heat Universal Lip Luminizer + Plumper', 'Ultra HD Soft Light Liquid Highlighter', 'Abeille Royale Anti-Aging Eye Cream', 'Prisme Libre Skin-Caring Matte Foundation', 'Hydra Life Cooling Hydration Sorbet Eye Gel', 'Mini Fluff Up Brow Flexible Brow-Texturizing Wax', "J'adore eau de parfum infinissime", 'Mini Vitamin Nectar Glow Juice Antioxidant Face Serum', 'Miss Dior Moisturizing Body Milk', 'Hydrabarrier Nourishing Face Oil', 'Sauvage After Shave Balm', 'Gentleman Eau de Parfum', 'Black Tea Anti-Aging Moisturizer with Retinol-Alternative BT Matrix', 'Fenty Icon Velvet Liquid Lipstick', 'Sugar Recovery Lip Mask Advanced Therapy', 'Crayon Eyeliner - Waterproof', 'Sauvage Elixir', 'Aqua Allegoria Flora Salvaggia Eau de Toilette', 'Cherry Treat Conditioning + Strengthening Lip Oil', "L'Interdit Eau de Parfum", 'Great Brow Basics Pencil & Gel Set', 'Rouge Blush', 'Truth Juice Daily Cleanser', 'Go Big or Go Home Long-Wear Vegan Volumizing Mascara', 'Poison', 'Abeille Royale Anti-Aging Eye Lifting Serum', 'L’Interdit Rouge Eau De Parfum', 'Rouge Artist For Ever Matte 24HR Longwear Liquid Lipstick', 'Sauvage Eau de Parfum', 'One Essential Eye Serum', 'KissKiss Liplift Lipstick Primer', 'Mon Guerlain Eau de Parfum', 'Aqua Resist Graphic Pen 24HR Waterproof Intense Eyeliner', 'Rice Sake Bath', 'Mini Sugar Face Polish Exfoliato', 'Banana Bright 15% Vitamin C Serum', 'Kombucha Antioxidant Facial Treatment Essence', 'Invisimatte Blotting Paper Refill', 'BACKSTAGE Eyeshadow Palette', 'Terracotta Matte Bronzer', 'Mini Prisme Libre Loose Powder', 'Miss Dior Hair Mist', 'Irresistible Eau de Parfum Rollerball', 'Capture Totale Firming & Wrinkle-Correcting Eye Cream', 'Aqua Resist Waterproof Tinted Eyebrow Gel', 'Miss Dior Eau de Parfum Roller-Pearl', 'Color Correcting Step 1 Primers', 'Hydra Vizor Invisible Moisturizer Broad Spectrum SPF 30 Sunscreen with Niacinamide Refill', 'Black Tea Firming and De-Puffing Eye Cream', 'Milk Hydrating Hand Cream', 'Mini Go Big or Go Home Long-Wear Vegan Volumizing Mascara', 'Dewtopia 20% Acid Night Treatment', 'Sauvage Parfum', 'Pi Eau de Toilette', 'Gimme Brow+ Tinted Volumizing Eyebrow Gel', 'Mini Truth Juice Daily Cleanser', 'Mini Soy pH-Balanced Hydrating Face Wash', 'The Glow Around 4-Piece Travel Skincare Essentials Set', 'Miss Dior Blooming Bouquet', 'Goof Proof Waterproof Easy Shape & Fill Eyebrow Pencil', 'Flypencil Longwear Pencil Eyeliner', 'Gimme Brow+ Volumizing  Fiber Eyebrow Pencil', 'Bright Fix Eye Brightener Concealer', 'Mini Kombucha Antioxidant Facial Treatment Essence', 'Good Apple Lightweight Full-Coverage Concealer', 'Sugar Triple-Action Lip Serum Advanced Therapy', 'Diorshow Stylo Waterproof Eyeliner', 'Pure Poison', 'Lemonade Smoothing Scrub', 'Step 1 Primer Shine Control', 'Matte Velvet Skin High Coverage Multi-Use Concealer', "Total Cleans'r Makeup-Removing Cleanser with Barbados Cherry", 'Match Stix Glow Skinstick', 'Mini Step 1 Primer Color Corrector – 24HR Redness Control & Hydrating Primer', 'Mini Gimme Brow+ Tinted Volumizing Eyebrow Gel', 'Match Stix Matte Contour Skinstick', 'Mini Goof Proof Waterproof Easy Shape & Fill Eyebrow Pencil', 'Terracotta Sunkissed Natural Bronzer', 'Mad Eyes Felt Matte Waterproof Eyeliner Pen', 'Aperitivo In Terrazza Diffuser', 'BeamCream Smoothing Body Moisturizer with AHAs', 'Pro Kiss’r Lip-Loving Scrubstick', 'Mini Gimme Brow + Volumizing Fiber Eyebrow Pencil', 'Very Irrésistible Eau de Toilette', 'Glow Strong Mini Moisturizer + Eye Cream Duo', 'Pout Preserve Peptide Lip Treatment', "They're Real! Magnet Extreme Lengthening Mascara", 'HD Skin Sponge', 'Mini Lemonade Smoothing Scrub', 'Ange ou Demon Le Secret Eau de Parfum', 'Mini Step 1 Primer Shine Control', 'Mini Hydra Vizor Invisible Moisturizer Broad Spectrum SPF 30 Sunscreen with Niacinamide', 'Saint Eau de Parfum Travel Spray', 'Renew + Recover Face + Eye Hydration Essentials', 'XO Vinyl Lip Cream Lip Gloss', 'Gentleman Boisee Eau de Parfum', 'ModCon Liquid-Gel Blush', 'Mini BeamCream Smoothing Body Moisturizer with AHAs', "L'Interdit Eau de Parfum Rollerball", 'Diorshow Maximizer 3D Triple Volume Plumping Lash Primer', "Mini They're Real! Magnet Extreme Lengthening Mascara", 'Miss Dior Eau de Parfum', 'Midnight Secret Late Night Recovery Treatment Anti-Fatigue Serum', 'Kitten Mini: Purrfect Cat Eyes Mini Mascara & Eyeliner Set', 'Invisimatte Blotting Paper', 'ModCon Long-Wear Hydrating Liquid-Gel Contour', 'Artist Color Pencil Brow, Eye & Lip Liner', 'Rouge Dior Ultra Care Liquid Lipstick', 'Dior Forever Glow Veil Makeup Primer', "Miss Dior Rose N'Roses Eau de Toilette", '156 Large Flat Blush Brush', 'High Brow Dual Ended Highlighting Eyebrow Pencil', 'Roller Liner Waterproof Liquid Eyeliner', 'Rouge G Refillable Lipstick Case', 'Rose & Squalane Deep Hydration Oil-Infused Serum', 'Flash Color Palette Multi-use Cream Color Palette', '226 Medium Eye Shader Brush', 'Sugar Lychee Body Lotion', '3 Mega Wonders', 'Aqua Allegoria Flora Cherrysia Eau de Toilette', '5 Couleurs Couture Eyeshadow Palette', 'Wrinkle Blur Bakuchiol Eye Gel Crème', 'Mini Roller Liner Waterproof Liquid Eyeliner', 'Gloss Bomb Ice', 'Rouge Artist Lipstick', 'Rouge Interdit Vinyl Color Enhancing Lipstick', 'Shalimar Eau de Parfum', 'Capture Totale Super Potent Rich Cream', 'Rose Floral Toner', 'Aqua Allegoria Orange Soleia Eau de Toilette', 'Mad Eyes Mascara Long-Wearing & Volumizing', 'Hydra Vizor Invisible Moisturizer Broad Spectrum SPF 30 Sunscreen with Niacinamide + Kalahari Melon', 'Gimme Brow+ Volumizing Eyebrow Gel Jumbo', 'The Professionall 24HR Double-Ended Lifting & Volumizing Mascara', 'Sugar Strawberry Exfoliating Face Wash', 'Floral Recovery Overnight Mask with Squalane', 'Dazzle Vegan Long-Wear Eyeshadow Stick', 'Gentle Eye Gel Waterproof Eye & Lip Makeup Remover', 'Irresistible Eau de Parfum Rose Velvet', 'Tattoo Liner Vegan Waterproof Liquid Eyeliner', 'Mini Gentle Eye Gel Waterproof Eye & Lip Makeup Remover', 'Butta Drop Whipped Oil Body Cream with Tropical Oils + Butters', 'Precision Blending Eyeshadow Brush 230', 'Mini Rose Floral Toner', 'Mini Sugar Strawberry Exfoliating Face Wash', 'Stay in Touch Restorative Hand Crème', 'Gloss Bomb Cream Color Drip Lip Cream', 'Mini Tattoo Liner Vegan Waterproof Liquid Eyeliner', 'Mini Floral Recovery Overnight Mask with Squalane', 'Everlasting Hyperlight Vegan Transfer-Proof Liquid Lipstick', 'Cookies N Clean Whipped Clay Pore Detox Face Mask with Salicylic Acid + Charcoal', "Eaze Drop'lit All-Over Glow Enhancer", 'Fenty Eau de Parfum', 'Full Cover Concealer', 'Colonia Pura', 'Lotus Youth Preserve Eye Cream', 'Super Pomade Vegan Eyeliner, Shadow & Brow Pigment', 'The Fenty Skin Soap Dish', 'Forever Perfect Fix Setting Spray', 'Mini Everlasting Hyperlight Vegan Transf

In [34]:
# Step 1: Preprocess the query
query = "miss dior"
query_processed = gensim.utils.simple_preprocess(query)

# Step 2: Get the Word2Vec embedding for the preprocessed query
query_embedding = model.wv[query_processed]

# Step 3: Calculate similarity between the query embedding and product name embeddings
df['similarity'] = df['product_name_processed'].apply(
    lambda x: model.wv.n_similarity(query_processed, x)
)

# Step 4: Sort the DataFrame based on similarity and get the most similar documents
result_df = df.sort_values(by='similarity', ascending=False)

# Extract the most similar documents and their similarity scores
most_similar_documents = result_df['product_name'].tolist()
similarity_scores = result_df['similarity'].tolist()

# Print or use the most similar documents and their similarity scores
for doc, score in zip(most_similar_documents, similarity_scores):
    if score >= 0.5:
        print(f"Document: {doc}, Similarity Score: {score}")

Document: Miss Dior Hair Mist, Similarity Score: 0.7529597282409668
Document: Miss Dior Absolutely Blooming, Similarity Score: 0.6680065393447876
Document: Miss Dior Blooming Bouquet, Similarity Score: 0.6668369770050049
Document: Miss Dior Eau de Parfum, Similarity Score: 0.6579596996307373
Document: Miss Dior Eau de Parfum Set, Similarity Score: 0.6017599701881409
Document: Miss Dior Body Oil, Similarity Score: 0.5815481543540955
Document: Miss Dior Eau de Toilette, Similarity Score: 0.5624021291732788
Document: Miss Dior Eau de Parfum Roller-Pearl, Similarity Score: 0.5520601868629456
Document: Miss Dior Rose N'Roses Roller-pearl, Similarity Score: 0.5331761837005615
Document: Miss Dior Blooming Bouquet Roller-pearl, Similarity Score: 0.511631429195404
Document: JOY by Dior, Similarity Score: 0.5090973973274231
Document: Miss Dior Moisturizing Body Milk, Similarity Score: 0.5017319321632385